website/models.py
from . import db
from flask_login import UserMixin


class Resource(db.Model):
    """Model forming the schema of information stored in our database
       for each resource. 

    Args:
        db (SQL database): the datbase in which information from the 
        model is persited. 
    """

    id = db.Column(db.Integer, primary_key=True)
    #id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    resource_name = db.Column(db.String(100), nullable=False)
    link_to_website = db.Column(db.String(255), nullable=False)
    resource_type = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), nullable=False)
    keywords = db.Column(db.ARRAY(db.String(500)), nullable=False)
    feedback = db.Column(db.ARRAY(db.Float), nullable=False)
    feedback_count = db.Column(db.Integer, nullable=False)
    rated_by_roster = db.Column(db.ARRAY(db.String(500)), nullable=False)

class User(db.Model, UserMixin):
    """Model forming the schema to represent each user of our service

    Args:
        db (SQL datbase): the database for which information for users
        is persisted.
    """
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))

    

website/__init__.py
from flask import Flask
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .authenticate import authenticate

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(authenticate, url_prefix='/')

    from .models import User

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'authenticate.signup'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    @app.route('/add_resource_page')
    def add_resource_page():
        return render_template('Add_resource_page.html', user=User)

    @app.route('/rate_resource_page')
    def rate_resource_page():
        return render_template('rate_resource_page.html', user=User)
    
    @app.route('/toc_page')
    def terms_of_conditions_page():
        return render_template('terms.html', user=User)

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, make_response, Flask, flash
from flask_login import login_required, current_user
from .models import Resource
from search import *
from . import db
from search import convert_description_to_array as convert
from flask_sqlalchemy import SQLAlchemy
import time

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    """To directs the user to the main page, send user to the sign up
    page when the website opens, as well as rednder search results 
    when a search is made.

    Returns:
        html template: render of or redirection to approprate page based on context.
    """
   
    if request.method == 'POST':
        category = request.form.get("category")
        q = request.form.get("q")

        if q and category:
            return redirect(url_for('views.search_results', category=category, q=q))
    return render_template("home.html", user=current_user)


@login_required
@views.route('/search_results', methods=['GET'])
def search_results():
    """Supprt user search requests by sending a dictionary of 
    found resoures to user.

    Returns:
        html template: sends results to the search.html template.
    """

    category = request.args.get('category')
    keyword_str = request.args.get('q')

    keywords = keyword_str.split(' ') if keyword_str else []
    keywords = remove_low_priority_keywords(keywords)
    results = []

    if keywords:
        results = Resource.query.filter(Resource.resource_type.ilike(f"%{category}%")).limit(5)

    filtered_results = set()
    filtered_results = find_resource_by_keyword_similarity(results, keywords)

    final = {}
    for i in filtered_results:
        final[i] = json.loads(i.feedback)
        
    response = make_response(render_template('search.html', results=final, user=current_user, refresh=1))
    response.headers['Cache-Control'] = 'no-store'

    return response

@login_required
@views.route('/add_resource')
def index_add_resource():
    """Renders the add_resource page when they click
        'Add resource' or when their attempt to add resource fails.

    Returns:
        html template: the template shown
    """
    return render_template('Add_resource_page.html', user=current_user)


@login_required
@views.route('/add_resource', methods=['POST'])
def add_resource():
    """Process user's resource addition, by ingesting it to the website
    and making user';s know if the respource was added or not by flahing messages.

    Returns:
        html template: template remains after the user adds a resource
    """

    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    db = SQLAlchemy(app)

    with app.app_context():
        resource_name = request.form['resource_name']
        link_to_website = request.form['link_to_website']
        resource_type = request.form['resource_type']
        email = request.form['email']
        keywords = request.form['keywords']

        if db.session.query(models.Resource).filter(
                    models.Resource.resource_name.ilike(f"%{resource_name}%")).first() is not None:
            flash("Resource already exists.", category='error')
        else: 
            rating, count, roster = json.dumps([0.0, 0.0]), 0, json.dumps([])
            new_resource = Resource(
                resource_name=resource_name,
                link_to_website=link_to_website,
                resource_type=resource_type,
                email=email,
                keywords=convert(keywords),
                feedback=rating,
                feedback_count=count,
                rated_by_roster=roster
            )

            db.session.add(new_resource)
            db.session.commit()
            db.session.close()
            flash("Resource added!", category='success')

    return redirect(url_for('views.index_add_resource'))


@views.route('/submit_rating')
def rate_resource_index():
    """Rendering the rate resource page.

    Returns:
        html template: the rate resource page
    """
    return render_template('rate_resource_page.html', user=current_user)


@views.route('/submit_rating', methods=['POST'])
def submit_rating():
    """Processes user's feedback, ingesting them into the database.

    Returns:
        html tenplate, db write: writes the rating the databse, and 
        redirects the user home.
    """
    resource_name = request.form.get('resource_name')
    accessibility = float(request.form.get('accessibility'))
    effectiveness = float(request.form.get('effectiveness'))
    updated_acc = 0
    updated_eff = 0

    resource = Resource.query.filter(Resource.resource_name.ilike(f"%{resource_name}%")).first()

    if resource:
        try:
            user_email = current_user.email
            existing_raters = json.loads(resource.rated_by_roster)

            if user_email not in existing_raters:
                existing_raters.append(user_email)

                feed_count = resource.feedback_count + 1
                curr_rating = json.loads(resource.feedback)
                updated_rating = []
            
                updated_acc = (curr_rating[0] + accessibility)/(feed_count)
                updated_eff = (curr_rating[1] + effectiveness)/(feed_count)
                
                updated_rating.append(updated_acc)
                updated_rating.append(updated_eff)

                resource.feedback = json.dumps(updated_rating)
                resource.rated_by_roster = json.dumps(existing_raters)
                resource.feedback_count = feed_count
                flash("Thanks for your feedback!", category='success')
            else:
                flash("You already rated this resource.", category='error')
            db.session.commit()
        except json.decoder.JSONDecodeError as e:
            print(f"Error decoding JSON for result: {e}")

    return redirect(url_for('views.rate_resource_index'))

website/templates/Add_resource_page.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='Add_resource_page.css') }}"
/>
<div class="AddResource">
  <h3>Are there any resources you would like to add?</h3>
  <br />
  <p>Please go ahead and enter the required information</p>
  <form action="/add_resource" method="post">
    <label for="resource_name"> Resource Name: </label>
    <br />
    <input
      type="text"
      class="input"
      id="resource_name"
      name="resource_name"
      autocomplete="off"
      placeholder="Ex: The Resource Center"
      required
    />
    <br />
    <br />
    <label for="link_to_website">
      Please include a webiste link if the resource has one:
    </label>
    <br />
    <input
      type="text"
      class="input"
      id="link_to_website"
      name="link_to_website"
      autocomplete="off"
      placeholder="Ex: https://www.wesleyan.edu/resourcecenter/"
    />
    <br />
    <br />
    <p>Select resource category:</p>
    <select name="resource_type" id="resource_type" required>
      <option value="Equity">Equity</option>
      <option value="Health">Health</option>
      <option value="Academics">Academics</option>
      <option value="Student Life">Student Life</option>
      <option value="Career">Career</option>
      <option value="Dining">Dining</option>
    </select>
    <br />
    <br />
    <label for="email">Email:</label>
    <br />
    <input
      type="email"
      class="input"
      id="email"
      name="email"
      autocomplete="off"
      placeholder="Please type your email"
      required
    />
    <br />
    <br />
    <label for="keywords"
      >Please provide a short description of the resource</label
    >
    <br />
    <input
      type="text"
      class="input"
      id="keywords"
      name="keywords"
      autocomplete="off"
      placeholder="Ex: Helps students with..."
      required
    />
    <br />
    <br />
    <button class="submit_btn" type="submit">Add Resource</button>
  </form>
</div>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='main_page.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='rate_resource_page_css.css') }}"
    />
    <link
      rel="stylesheet"
      href=" {{ url_for('static', filename= 'Add_resource_page.css') }}"
    />
    <link
      rel="stylesheet"
      href=" {{ url_for('static', filename= 'sign-In.css') }}"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    {% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
        fetch("/delete-note", {
          method: "POST",
          body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
          window.location.href = "/";
        });
      }
    </script>
    {% endblock %}
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
  %}
  <link rel="stylesheet" href="{{ url_for('static', filename='main_page.css') }}"> 
    <div class="MainPage">
      <label class="hamburger-menu">
        <input type="checkbox" /> 
      </label>
      <aside class="sidebar">
        <nav>
          <div>
            <p> <a href="{{ url_for('add_resource_page') }}"> Add Resource </a> </p>
          </div>
          <div>
            <p> <a href="{{ url_for('rate_resource_page') }}"> Rate a Resource </a> </p>
            <!-- <p> <a href="#" id="rateResourceLink">  </a> </p> -->
          </div>
          <div><p> <a href="{{ url_for('terms_of_conditions_page') }}"> Terms of Services </a></div>
        </nav>
      </aside>
      <div class="main-part">
        <form class="form" method="POST" autocomplete="off">
        <h1 class = "welcome">Welcome to Wesfind!</h1>
        <p> Simply select a category and share your concern. 
          We'll help identify the most suitable resources at Wesleyan to address your issue! </p>
      <p>
        Select resource type:
      </p>
        <select class = "input" name="category" id="category">
            <option value="">Resource type</option>
            <option value="Equity">Equity</option>
            <option value="Health">Health</option>
            <option value="Academics">Academics</option>
            <option value="Dining">Dining</option>
            <option value="Career">Career</option>
            <option value="Student Life">Student Life</option>
            <option value="Other">Other</option>
          </optgroup>
        </select>
        <br>
        <section class="section">
          <div class="columns">
            <div class="column is-one-third is-offset-one-third">
              <p>
                <br>
                Describe what you need in a few words...
              </p>
              <input type="text" class="input" placeholder="Enter description" name="q" hx-get="/search2" hx-trigger="keyup changed delay:500ms" hx-target="#results">
            </br>
          </br>
            </div>
      </div>
      <button class ="submit_btn"> Find resource </button>
    </form>
  </div>
    </section>
  </div>
  </div>
{% endblock %}
  

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div class="Sign_up_page">
  <div class="web_description">
    <h2 class="Webname">Wesfind</h2>
    <p>
      Explore a centralized hub for Wesleyan resources, bringing together a
      wealth of information in one convenient location!
    </p>
  </div>
  <div class="sign_up_form">
    <div class="login-signUp-page">
      <form class="form_signUP" method="POST" , autocomplete="off">
        <h3 align="center">Login</h3>
        <div class="form-group">
          <label for="email"> Email Address </label>
          <input
            type="email"
            class="input_singUP"
            id="email"
            name="email"
            placeholder="Enter email"
          />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input
            type="password"
            class="input_singUP"
            id="password"
            name="password"
            placeholder="Enter password"
          />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

website/templates/rate_resource_page.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
<link rel="stylesheet" href="{{ url_for('static', filename='rate_resource_page_css.css') }}"> 

    <div class="RateResource">
    <form id="ratingForm" class="ratingForm" action="{{ url_for('views.submit_rating') }}" method="POST">
        <label for = "resourceName"> Resource Name: </label>
        <input type="text" id="resourceName" name="resource_name" autocomplete="off" required >
    </br>
    <div class = "evaluators">
    <label for="accessibility">Accessibility: </label>
    <input type="range" id="accessibility" name="accessibility" min="0" max="5" step="1" value="0">
    <span id="accessibilityValue">0</span> 
  </br>
    <label for="effectiveness">Effectiveness: </label>
    <input type="range" id="effectiveness" name="effectiveness" min="0" max="5" step="1" value="0">
    <span id="effectivenessValue">0</span>
  </br>
</div>
    <input type="submit" class = "submit_button" value=" Submit Rating ">
  </form>
  </div>


  <script>
    var accessibilityInput = document.getElementById('accessibility');
    var effectivenessInput = document.getElementById('effectiveness');
    
    var accessibilityValue = document.getElementById('accessibilityValue');
    var effectivenessValue = document.getElementById('effectivenessValue');

    accessibilityInput.addEventListener('input', function() {
        accessibilityValue.textContent = accessibilityInput.value;
    });

    effectivenessInput.addEventListener('input', function() {
        effectivenessValue.textContent = effectivenessInput.value;
    });
</script>

{% endblock %}
        
      

website/templates/search.html
{% extends "base.html" %}
{% block title %}Results{% endblock %}
{% block content %}
  </head>
  <body>
    <br><br>
    <h3>Available resource(s)</h3><br>
    {% if results %}
      <style>
        .search_table {
          border-collapse: collapse;
          width: auto; /* Let the table adjust to the content */
        }

        .search_table th, .search_table td {
          padding: 20px; /* Adjust the padding as needed */
          border: 1px solid #ddd; /* Optional: add borders for better visibility */
        }
      </style>
      <table class="search_table">
        <thead>
          <tr>
            <th>Resource Name</th>
            <th>Email</th>
            <th>Website</th>
            <th>Ratings (out of 5)</th>
          </tr>
        </thead>
        <tbody>
          {% for key, value in results.items() %}
            <tr>
              <td>{{ key.resource_name }}</td>
              <td>{{ key.email }}</td>
              <td>{% if key.link_to_website %}
                <a href="{{ key.link_to_website }}" target="_blank">Learn more</a>
              {% else %}
                N/A
              {% endif %}</td>
              <td>
                Accessibility: {{ value[0]|float|round(2) }}<br>
                Effectiveness: {{ value[1]|float|round(2) }}<br>
                Number of ratings: {{ key.feedback_count }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No results found.</p>
    {% endif %}
  </body>
</html>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<link rel="stylesheet" href="{{ url_for('static', filename='sign-In.css') }}" />
<div class="Sign_up_page">
  <div class="web_description">
    <h2 class="Webname">Wesfind</h2>
    <p>
      Explore a centralized hub for Wesleyan resources, bringing together a
      wealth of information in one convenient location!
    </p>
  </div>
  <div class="sign_up_form">
    <form method="POST" , autocomplete="off">
      <h3 class="title" align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="input_singUP"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="input_singUP"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="input_singUP"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="input_singUP"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <p>
        Already have an account?
        <a href="{{ url_for('authenticate.login') }}">Login here!</a>
      </p>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

website/templates/terms.html
{% extends "base.html" %}
{% block title %}Terms{% endblock %}
{% block content %}
    <div class="textbox" id="textbox">
        <span class="close" onclick="toggleTextbox()">&times;</span>
        <h2>Terms of Conditions</h2>
<div>
    <ul>
        <li><strong>Purpose:</strong> Submissions must be intentional and positively contribute to the Wesleyan University community.</li>
        <li><strong>Responsibility:</strong> Feel free to spread the word to help out your fellow peers!</li>
        <li><strong>Feedback:</strong> Contact the creators only at <a href="mailto:rosbourne@wesleyan.edu">rosbourne@wesleyan.edu</a> or <a href="mailto:mgebremeskel@wesleyan.edu">mgebremeskel@wesleyan.edu</a> for serious suggestions or concerns.</li>
    </ul>
</div>

    <script src="{{ url_for('static', filename='terms.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='terms.css') }}">
{% endblock %}